import { db } from "@/lib/db";
import { MockInterview } from "@/utils/schema";
import { desc } from "drizzle-orm";

import QuestionsContent from "@/components/ui/QuestionsContent";

export default async function QuestionsPage() {
  const interviews = await db
    .select()
    .from(MockInterview)
    .orderBy(desc(MockInterview.id));

  return (
    <div className="min-h-screen bg-slate-50">

      <div className="mx-auto max-w-7xl px-6 py-10">

        {/* Header */}

        <div className="mb-10">

          <p className="text-sm font-semibold uppercase tracking-widest text-violet-600">
            Question Bank
          </p>

          <h1 className="mt-2 text-4xl font-bold text-slate-900">
            AI Interview Questions
          </h1>

          <p className="mt-3 max-w-2xl text-slate-500">
            Review every interview question generated by AI.
            Expand each interview to revise the correct answers
            whenever you want.
          </p>

        </div>

        {interviews.length === 0 ? (

          <div className="rounded-3xl border border-dashed bg-white p-20 text-center">

            <h2 className="text-2xl font-semibold">
              No Questions Found
            </h2>

            <p className="mt-3 text-slate-500">
              Create your first interview to build your personal question bank.
            </p>

          </div>

        ) : (

          <QuestionsContent interviews={interviews} />

        )}

      </div>

    </div>
  );
}