interface FeedbackHeaderProps {
  average: string;
  performance: string;
  totalQuestions: number;
  answeredQuestions: number;
}

export default function FeedbackHeader({
  average,
  performance,
  totalQuestions,
  answeredQuestions,
}: FeedbackHeaderProps) {
  const progress = Number(average) * 10;

  // Ring geometry for the score indicator
  const radius = 54;
  const circumference = 2 * Math.PI * radius;
  const dashOffset = circumference * (1 - progress / 100);

  const stats: { label: string; value: string | number }[] = [
    { label: "Questions", value: totalQuestions },
    { label: "Answered", value: answeredQuestions },
    { label: "Average", value: `${average}/10` },
    { label: "Result", value: performance },
  ];

  return (
    <div className="relative overflow-hidden rounded-3xl bg-[#0B1220] p-8 shadow-2xl sm:p-10">
      {/* Ambient background accent */}
      <div
        aria-hidden
        className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-indigo-600/30 blur-3xl"
      />
      <div
        aria-hidden
        className="pointer-events-none absolute -left-16 bottom-0 h-56 w-56 rounded-full bg-amber-500/10 blur-3xl"
      />

      <div className="relative flex flex-col gap-10 lg:flex-row lg:items-center lg:justify-between">
        {/* Left: identity + headline */}
        <div className="max-w-xl">
          <p className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-indigo-300">
            <span className="h-1.5 w-1.5 rounded-full bg-amber-400" />
            AI Interview Report
          </p>

          <h1 className="mt-3 text-3xl font-bold tracking-tight text-white sm:text-4xl">
            Interview completed
          </h1>

          <p className="mt-3 text-base leading-relaxed text-slate-400">
            Here&apos;s your complete performance analysis, generated by AI
            from your interview session.
          </p>
        </div>

        {/* Right: score ring, the signature element */}
        <div className="flex flex-col items-center gap-3">
          <div className="relative flex h-36 w-36 items-center justify-center">
            <svg
              viewBox="0 0 120 120"
              className="h-36 w-36 -rotate-90 transform"
            >
              <circle
                cx="60"
                cy="60"
                r={radius}
                fill="none"
                stroke="rgba(255,255,255,0.08)"
                strokeWidth="10"
              />
              <circle
                cx="60"
                cy="60"
                r={radius}
                fill="none"
                stroke="#F59E0B"
                strokeWidth="10"
                strokeLinecap="round"
                strokeDasharray={circumference}
                strokeDashoffset={dashOffset}
                className="transition-all duration-700 ease-out"
              />
            </svg>

            <div className="absolute flex flex-col items-center">
              <span className="font-mono text-4xl font-bold tabular-nums text-white">
                {average}
              </span>
              <span className="text-[11px] uppercase tracking-wide text-slate-400">
                out of 10
              </span>
            </div>
          </div>

          <span className="rounded-full border border-white/10 bg-white/5 px-4 py-1.5 text-sm font-medium text-slate-200">
            {performance}
          </span>
        </div>
      </div>

      {/* Progress bar */}
      <div className="relative mt-10">
        <div className="mb-2 flex items-center justify-between text-xs font-medium uppercase tracking-wide text-slate-400">
          <span>Performance</span>
          <span className="font-mono text-slate-300">{progress}%</span>
        </div>

        <div className="h-2 w-full overflow-hidden rounded-full bg-white/5">
          <div
            className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-amber-400 transition-all duration-700 ease-out"
            style={{ width: `${progress}%` }}
          />
        </div>
      </div>

      {/* Stats row */}
      <div className="relative mt-10 grid grid-cols-2 gap-6 border-t border-white/10 pt-8 sm:grid-cols-4 sm:divide-x sm:divide-white/10">
        {stats.map((stat) => (
          <div key={stat.label} className="sm:px-6 sm:first:pl-0">
            <p className="text-xs uppercase tracking-wide text-slate-400">
              {stat.label}
            </p>
            <p className="mt-1.5 truncate text-2xl font-semibold text-white">
              {stat.value}
            </p>
          </div>
        ))}
      </div>
    </div>
  );
}