interface FeedbackHeaderProps {
  average: string;
  performance: string;
  totalQuestions: number;
  answeredQuestions: number;
}

export default function FeedbackHeader({
  average,
  performance,
  totalQuestions,
  answeredQuestions,
}: FeedbackHeaderProps) {
  const progress = Number(average) * 10;

  return (
<div className="rounded-3xl bg-violet-600 text-white shadow-xl p-8">
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-8">

        {/* Left */}

        <div>
          <p className="text-violet-200 font-medium">
            AI Interview Report
          </p>

          <h1 className="text-4xl font-bold mt-2">
            Interview Completed 🎉
          </h1>

          <p className="text-violet-100 mt-3 text-lg">
            Here's your complete interview performance analysis generated by AI.
          </p>
        </div>

        {/* Right */}

        <div className="text-center">

          <div className="text-6xl font-extrabold">
            {average}
          </div>

          <p className="text-violet-100">
            Overall Score /10
          </p>

          <div className="mt-3 inline-flex rounded-full bg-white/20 px-4 py-2">
            {performance}
          </div>

        </div>

      </div>

      {/* Progress */}

      <div className="mt-8">

        <div className="flex justify-between text-sm mb-2">
          <span>Performance</span>
          <span>{progress}%</span>
        </div>

        <div className="h-3 rounded-full bg-white/20 overflow-hidden">

          <div
            className="h-full rounded-full bg-white transition-all duration-700"
            style={{
              width: `${progress}%`,
            }}
          />

        </div>

      </div>

      {/* Stats */}

      <div className="grid grid-cols-2 md:grid-cols-4 gap-5 mt-8">

        <div className="rounded-2xl bg-white/10 p-5 backdrop-blur">
          <p className="text-violet-200 text-sm">
            Questions
          </p>

          <h2 className="text-3xl font-bold mt-1">
            {totalQuestions}
          </h2>
        </div>

        <div className="rounded-2xl bg-white/10 p-5 backdrop-blur">
          <p className="text-violet-200 text-sm">
            Answered
          </p>

          <h2 className="text-3xl font-bold mt-1">
            {answeredQuestions}
          </h2>
        </div>

        <div className="rounded-2xl bg-white/10 p-5 backdrop-blur">
          <p className="text-violet-200 text-sm">
            Average
          </p>

          <h2 className="text-3xl font-bold mt-1">
            {average}
          </h2>
        </div>

        <div className="rounded-2xl bg-white/10 p-5 backdrop-blur">
          <p className="text-violet-200 text-sm">
            Result
          </p>

          <h2 className="text-xl font-bold mt-2">
            {performance}
          </h2>
        </div>

      </div>

    </div>
  );
}